name: capstone_pipeline

on:
  push:
    branches:
      - master

jobs:
  deployment:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: aws-configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ AKIARBR3KPW2HFX3J5TS }}
          aws-secret-access-key: ${{ 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 }}
          aws-region: us-east-2

      - name: install kubectl
        uses: aws-actions/setup-kubectl@v3
      
      - name: install terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: run terraform init
        run: | 
          cd infrastructure 
          terraform init

       
      - name: terraform plan
        run: |
          cd infrastructure
          terraform plan

      - name: apply terraform
        run: |
          cd infrastructure
          terraform apply

      - name: update kubectl credentials
        run: aws eks update-kubeconfig --name Senaike-eks-1pHs5aYO --region us-east-2

      - name: deploy cluster
        run: kubectl apply -f complete-demo.yaml
     
    
